### ISSUE TITLE
Layout bug with latest code insiders build

### ISSUE THREAD

**Issue by warpdesign** [arcticicestudio/nord-visual-studio-code#101]
This is what I get when opening 3 tabs, and the settings panel in the middle one with recent Code insider builds:

![image](https://user-images.githubusercontent.com/199648/46040634-22f6bb00-c111-11e8-8c04-2ffe1090c8d9.png)

Here is what the web inspector shows:

![image](https://user-images.githubusercontent.com/199648/46040478-b380cb80-c110-11e8-8741-d652476b0927.png)

This does not happen with any other themes (either built-in or third-party).

I also opened an issue in [VSCode](https://github.com/Microsoft/vscode/issues/59217).

**Comment by warpdesign** [comment]
This is fixed in latest insider.

**Comment by arcticicestudio** [comment]
@warpdesign Thanks for your contribution 👍 and nice to hear it got fixed. My guess was also that it must be problem of VS Code itself since the theme only defines colors, there it absolutely nothing related to any layout styles like e.g. margins/paddings etc.
The fact that it was reproducible with this theme might be related to the transparent colors used for theme keys that are not used, but should be included in case they will be used in the future (and also to know about them since there are many keys that are not documented atm.)
