### ISSUE TITLE
Code inside the peek window is unreadable

### ISSUE THREAD

**Issue by KasiMaru** [arcticicestudio/nord-visual-studio-code#119]
Hi, thanks for the awesome theme!

Currently the code that gets matched and auto hightligted in Peek window has a background that is too bright and, as a result, highlighted code is almost unreadable:

<img width="1433" alt="index js — penguin-event 2019-04-03 17-31-00" src="https://user-images.githubusercontent.com/26373955/55488171-32af0900-5638-11e9-852e-cb6e253e2dfe.png">

The theme setting that should be tweaked is `peekViewEditor.matchHighlightBackground`

**Comment by arcticicestudio** [comment]
Hi @KasiMaru :wave:, thanks for your contribution :+1:
Can you please try the `develop` branch, the problem was fixed in #112 but the next release version has not been packed and deployed yet.
To use the theme with the `develop` branch uninstall the Nord extension, clone this repository to your extension folder and rename it to `arcticicestudio.nord-visual-studio-code` followed by a dash (`-`) and any version number, e.g. `-0.7.0` (complete folder name: `arcticicestudio.nord-visual-studio-code-0.7.0`.
See [official documentation: "Where are extensions installed?"][doc] for details about the folder locations on different OS.

Restart VS Code and select the theme again. It will now use the `develop` branch that is the default branch of the repository.
Also if you like to always use the latest (maybe unstable) development state of the theme you can keep the folder like this and run a `git pull --ff-only --prune` from time to time.

[doc]: https://code.visualstudio.com/docs/editor/extension-gallery#_where-are-extensions-installed

**Comment by KasiMaru** [comment]
@arcticicestudio Oops, sorry, should've looked into the closed PRs! Yep, changes in the develop branch do fix the problem! I'll close this issue 🙇‍♂️

**Comment by arcticicestudio** [comment]
No problem, glad to see if works fine :smile:
