### ISSUE TITLE
Background color for selected item in explorer view makes text difficult to read

### ISSUE THREAD

**Issue by obahareth** [arcticicestudio/nord-visual-studio-code#144]
## Description

Selected items in the explorer view have almost no contrast and it's very difficult to read the selected file's name.

### Steps to Reproduce

1. Select an item in the explorer view.
2. Observe the background color

### Expected Behavior

What you expect to happen?
That there is enough contrast between the text color and selected color.

### Actual Behavior

What actually happens?
The contrast between the text color and selected color is too similar and they're very hard to read.

## Environment and Versions

- What is the version of _Nord Visual Studio Code_ you are running? 0.10.0
- What is the name and the version of your OS? macOS Mojave 10.14.5
  - Have you tried to reproduce it on different OS environments and if yes is the behavior the same for all? No I have not tried.

## Additional Context

An example in the screenshot is the file `clearhaus.rb`.

Add any other context, screenshots or screencasts which are relevant for this issue.
<img width="381" alt="Screen Shot 2019-06-23 at 1 28 31 PM" src="https://user-images.githubusercontent.com/3428118/59974973-65272d00-95bb-11e9-9ba4-2de20e6ea4b9.png">

**Comment by arcticicestudio** [comment]
Hi @obahareth :wave:, thanks for your contribution :+1:
I tried to reproduce this, but the foreground color of the selected item looks fine and uses `nord0` like expected (VS Code workbench theme key `list.activeSelectionForeground`).

Are there any other extensions installed that apply a different highlighting to e.g. show Git status effects or and linting errors. A way to test this is to disable all installed third-party extensions except Nord. Also if you're using [custom CSS/JS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) code, please revert the changes before disabling all other extensions.

**Comment by obahareth** [comment]
@arcticicestudio I'm not using any custom CSS/JS, and I disabled all extensions and I still see the same behavior.

**Comment by arcticicestudio** [comment]
This is strange 🤔 
What's the version of VS Code you're running? Maybe there are changes to the highlighting style or new/changed theme keys that resulting in a different foreground color.

**Comment by obahareth** [comment]
I was on the May version and now on the June version (1.36) and I still see the same behavior. This only happens when I click on an item in the explorer view. If I click back  to focus on the code view, it goes away. 

I also just now tried downloading VS Code on a Windows machine that never had it installed and only installed the Nord theme and I see the same behavior.

I realize describing this is tricky, so here's a GIF:
![Kapture 2019-07-08 at 19 11 54](https://user-images.githubusercontent.com/3428118/60825429-58f2c080-a1b4-11e9-8ceb-23ad065204bf.gif)

The annoying color shows up when I click on anything in the explorer view, and it goes away when I click on the code view.

**Comment by arcticicestudio** [comment]
I've created a fresh throwaway VirtualBox with Windows 10, installed Nord and "unfortunately" were not able to reproduce this.

Also I think somethings needs to be clarified to make sure we're not talk past each other:
**The background color of selected items is by design**, but **the problem here is the "cyanish" foreground color**. When the project view is selected is uses `nord8` as background color while is changes to `nord2` when not focused anymore. This is by design to ensure the brighter `nord8` selection color so it does not interfere when trying to focus on the actual code.

I can also see on your screencast that there must either be some other extensions active or some custom user settings regarding the workbench UI/editor syntax highlighting.
The color of the brackets is not the style of Nord (they only use `nord6`), but your screencast shows some kind of “rainbow braces“ where each line uses different colors. If this is a active extension it might be possible that it also changes the foreground color of the selected item in the project view.

Can you please post your `settings.json` (command palette → “Preferences: Open Settings (JSON)“) located in your `~/.vscode` directory as well as the output when running `code --list-extensions`?
This way I can check which extensions are active and try to reproduce the problem when using your exact same settings.

**Comment by obahareth** [comment]
Oh wow you're right, I hadn't noticed the rainbow brackets... that is really weird. I had just installed VS Code on that machine and only installed Nord but you're absolutely right... I'll find the culprit and update this issue in case anyone else faces this issue.

**Comment by obahareth** [comment]
Thanks for suggesting opening the JSON version of the settings, I totally forgot to check for that. I don't even know how my Windows machine got these settings (I must have copied something years ago and forgotten about it 😰). The cuprit was something overriding `workbench.colorCustomizations` in my settings. I'm so sorry for taking up so much of your time on this.

**Comment by arcticicestudio** [comment]
Don't worry, that's part of maintaining and why this issue is also sorted into the “Support“ board. When maintaining some open source projects over years an important task to learn is to always try to reproduce with a "clean" environment.
Anyway, glad to see you solved it and can use the theme without limitations again 😄
