### ISSUE TITLE
Icons not distinguishable

### ISSUE THREAD

**Issue by maharjanaman** [arcticicestudio/nord-visual-studio-code#146]
Can't recognizes icons in this sections
<img width="383" alt="Screen Shot 2019-07-08 at 13 31 54" src="https://user-images.githubusercontent.com/14164484/60792346-41501380-a185-11e9-95c1-1c7012081e82.png">

**Comment by arcticicestudio** [comment]
Hi @maharjanaman :wave:
Which icons do you mean? There are multiple icons visible on the screenshot: file icons, action bar icons or the sidebar icons?

**Comment by maharjanaman** [comment]
Sorry about lack of clarification. Here is same image with red circle. These icons are quite hard to see when an item is selected.
Hope below image clarifies things a lot.

<img width="383" alt="Screen Shot 2019-07-08 at 13 31 54" src="https://user-images.githubusercontent.com/14164484/60804651-b4658400-a19d-11e9-829c-f51e65f2b124.png">

**Comment by arcticicestudio** [comment]
Unfortunately there is no theme key that allows to customize these icons, they are "hardcoded" in VS Code and as far as I know there is also no (official) way to modify these. In my personal VS Code setup I've also removed all these VS Code icons via the [Custom CSS and JS Loader][ext] extension (except file icons) since all they functions can be called using the command bar.

To solve your problem you could also try to use the CSS/JS loader extension to change their color. If you don't want to install the extension another way would be to override Nord's highlighting style for selected items. Please read [Nord's official documentation about theme customization][doc] for a detailed guide to apply  custom highlighting only for the Nord theme.

[ext]: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
[doc]: https://www.nordtheme.com/docs/ports/visual-studio-code/customization

**Comment by arcticicestudio** [comment]
@maharjanaman Have you been able to customize the icons using the proposed methods? If yes, please close this ticket.
Also the latest VS Code version also introduced new icons, so maybe there will be an official way to customize them later on.

**Comment by maharjanaman** [comment]
Haven't tried using Custom CSS and JS Loader extension but closing this now.

**Comment by arcticicestudio** [comment]
@maharjanaman It looks like the next version will include new workbench theme keys to customize icons based on their refactoring to extract all icons into a custom icon font.

- [`icon.foreground`][c1]
- [`editorLightBulbForeground` and `editorLightBulbAutoFixForeground`][c2]
- [`notificationsErrorIcon.foreground`, `notificationsWarningIcon.foreground` and `notificationsInfoIcon.foreground`][c3]

I'll track the changes and check the changelogs to add support to Nord for it.

[c1]: https://github.com/microsoft/vscode/blob/73c61c4e40e949d0809f6f2882c273f9b849bf75/src/vs/platform/theme/common/colorRegistry.ts#L182
[c2]: https://github.com/microsoft/vscode/blob/73c61c4e40e949d0809f6f2882c273f9b849bf75/src/vs/platform/theme/common/colorRegistry.ts#L341-L345
[c3]: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/common/theme.ts#L562-L578
