### ISSUE TITLE
is anyone working on light theme

### ISSUE THREAD

**Issue by swapnilsarwe** [arcticicestudio/nord-visual-studio-code#164]
Hey is there anyone who is working on the light theme for the nord.

Never worked on the vs code plugins, but would love to contribute in someway or the another, if no one has picket it up, may i will give it a try and send a PR to review.

**Comment by arcticicestudio** [comment]
Hi @swapnilsarwe, thanks for your contribution offering :+1: 
There are plans to implement a "light" mode/variant like described in https://github.com/arcticicestudio/nord/issues/46, but this is currently not the project scope. Feel free to go ahead and start implement it if you like to, but also please note that it'll take some time until it can be reviewed and merged since it should be supported in all port projects at the same time.
