### ISSUE TITLE
Adopt semantic highlighting

### ISSUE THREAD

**Issue by aeschli** [arcticicestudio/nord-visual-studio-code#172]
Since 1.43, VSCode themes can take advantage of [semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting).

Every theme controls whether semantic tokens are enabled. So far, only built-in themes have it enabled and I filed this issue to ask you to opt-in for the Nord theme as well.

Adoption is easy and there are new cool styling possibilities.

To turn on semantic highlighting for a theme, all you have to do is put
`"semanticHighlighting": true`
in the theme's definition file.

There's a good chance that no further change to the theme is needed (thanks to a default mapping from semantic tokens to TextMate scopes (if not, I'd be interested to know, so I can improve the defaults further)). 

But, more interestingly, themes can tune and go wild by defining new styling rules against the semantic tokens:
```json
"semanticTokenColors": {
    "variable.readonly": "#ff0000", 
    "parameter": { "fontStyle": "underline" },
    "*.declaration:java": { "fontStyle": "bold" }
} 
```

Check out our [Semantic Highlighting Wiki](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) and the [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for more details and feel free to ping me in this issue if I can help.

Thanks for the great work and looking forward to semantic highlighting in your theme.

**Comment by arcticicestudio** [comment]
Hi @aeschli :wave:, thanks for your contribution :+1:
Nice to see you involve the community even more on this way 😄 

I read release notes for my personal use as well as for changes related to the theme API every time a new VS Code version gets published. Therefore I've already [created a note in the repository backlog][n] to learn more about _semantic highlighting_. Also enabled it locally some weeks ago to take a quick look and disabled it again since it broke a lot of colors, but after reading through the latest change logs and PRs in the VS Code repository I guess this is fixed by now.

There are currently a lot other tasks for other projects and Nord ports as well as for my job due to the current world health situation, but I definitely planned to adapt to it within the next weeks.

[n]: https://github.com/arcticicestudio/nord-visual-studio-code/projects/2#card-36003174

**Comment by nomenon** [comment]
https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.19-beta1

**Comment by arcticicestudio** [comment]
@nomenon How is this related to this issue?

---

Status report so far after enabling _semantic highlighting_ on my local machine and using it for some weeks: Works fine for different languages. I haven't had any issues or noticed any broken highlighting. Sometime it takes some seconds until the highlighting is updated, but this also depends on the current workload of the system as well as the project size and number of lines in the opened files.

I'll continue to use it locally until the weekend, but I guess it should be fine to merge the change and release a new extension version to roll it out to the users for more feedback.
