### ISSUE TITLE
publish to open-vsx.org

### ISSUE THREAD

**Issue by Dreckiger-Dan** [arcticicestudio/nord-visual-studio-code#180]
## Description

I use [VSCodium](https://github.com/VSCodium/vscodium) instead of VSCode. They [recently ditched](https://github.com/VSCodium/vscodium/pull/404) the [Visual Studio Marketplace](https://marketplace.visualstudio.com/vscode) in favour of [Open VSX](https://open-vsx.org). I'd love if you published the theme on this marketplace as well.

### Benefits

Open VSX is vendor neutral and used by editors like [VSCodium](https://github.com/VSCodium/vscodium) or [Eclipse Theia](https://theia-ide.org/). By publishing to this marketplace you would reach more users that use different editors.

### Alternative Solutions

In the meantime you can of course manually install the theme via the vsix file. But this way the theme is not as discoverable and easy to install/update on Non-Microsoft editors.

## References

* [VSCodium](https://github.com/VSCodium/vscodium)
* [Open VSX](https://open-vsx.org)
* [Open VSX Repo](https://github.com/eclipse/openvsx)
* [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki)
* [Publishing Extensions on Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by arcticicestudio** [comment]
Hi @Dreckiger-Dan :wave:, thanks for your contribution :+1:

I've seen _VSCodium_ some time ago on my GitHub explore timeline, but haven't seen that it's related to _Eclipse_. Anyway, I guess publishing to another registry shouldn't be too much overhead and tasks like this will be automated with GitHub Actions in some time anyway.

I've created an account and already published the extension (I guess the `-visual-studio-code` extension name suffix should be fine) and also submitted eclipse/open-vsx.org#58 to claim ownership for the `arcticicestudio` namespace 😄 
I'll leave this issue open in order to adjust the documentation so users are aware that _Nord_ is also now available from the _Open VSX_ extension marketplace.

**Comment by svengreb** [comment]
Closing this issue because the theme [has been available on the marketplace for a long time][1].

[1]: https://open-vsx.org/extension/arcticicestudio/nord-visual-studio-code
