### ISSUE TITLE
Add semantical highlighting for method arguments

### ISSUE THREAD

**Issue by dynobo** [arcticicestudio/nord-visual-studio-code#181]
## Metadata Head

> Related issues:  #172 

## Description

The current support for [semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting) in Nord doesn't highlight **method arguments**. 

Compare e.g. formatting of the argument `entries` in Nord theme and [Mayukai Theme](https://marketplace.visualstudio.com/items?itemName=GulajavaMinistudio.mayukaithemevsc):

Nord:
![semantic_2](https://user-images.githubusercontent.com/11071876/94339100-a9dc1800-fff7-11ea-9c8b-9c5d3af40cde.png)

Mayukai Semantic Mirage:
![semantic_1](https://user-images.githubusercontent.com/11071876/94339104-ad6f9f00-fff7-11ea-9d9e-f6bed7454dc1.png)

I tested only Python and do not know, if this is relevant for other languages as well.

### Benefits

I find this particular highlighting to be very useful and would love to see it implemented in Nord, too.

### Possible Drawbacks

As semantic hightlighting can be also disabled in VS Code gloally, I do not se a drawback

Thanks! :-)

**Comment by arcticicestudio** [comment]
Hi @dynobo :wave:, thanks for your contribution :+1:
Syntax elements like [variables/constants are colored by `nord4`][stg] which is by design. That also applies when used as function/method parameter. This style was already used before #172 was merged.

If you'd like to change VS Code allows to locally override specific theme keys without the need to change any of the theme  code. Please see the [Nord VS Code customization documentation][c] as well as the [official VS Code docs about how to customize a theme extension][vscd].

[stg]: https://www.nordtheme.com/docs/colors-and-palettes#nord4
[c]: https://www.nordtheme.com/docs/ports/visual-studio-code/customization
[vscd]: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by dynobo** [comment]
Thanks for the info! Then I will just customize it like you described :-)
