### ISSUE TITLE
Possibility to trigger the request for checking updates inside the app itself as button 

### ISSUE THREAD

**Issue by iflare3g** [arcticicestudio/nord-visual-studio-code#249]
It'd be great to have a button inside the app to trigger the request for updates, the same that runs in background that generates the red circle to the Leapp icon.
Because sometimes I have the update notifiy icon, but it doesn't show me the usual popup to trigger the download of the upgrade. 

## Additional Context

Nothing

## References

Nothing

## Potential Solution

Button around the app like Check for updates of JetBrains products.

Thanks!

**Comment by svengreb** [comment]
Hi @iflare3g :wave:

I guess you confused the application, repository and the responsible component. This is a theme for Visual Studio Code and not the Jetbrains products. Your description also sounds like you're requesting an improvement for the product itself because a UI/syntax theme has nothing to do with update functionality at all.
Feature requests and improvement suggestions for JetBrains products can be submitted to [their YouTrack instance][1].

[1]: https://youtrack.jetbrains.com

**Comment by iflare3g** [comment]
Argh! My really bad sorry!
