### ISSUE TITLE
Change color of word "reference" from referencesCodeLens

### ISSUE THREAD

**Issue by yurlovm** [arcticicestudio/nord-visual-studio-code#33]
Hello, thanks for awesome theme!
Could you please investigate if it's possible to change color of word "reference" in code if option 
"typescript.referencesCodeLens.enabled" is true.
![screenshot_2](https://user-images.githubusercontent.com/10223137/27798175-b8744c82-6029-11e7-8b5f-c516f2dbc0c8.png)

**Comment by arcticicestudio** [comment]
It can be customized using the `editorCodeLens.foreground` selector which has been added to the latest theme version [0.4.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.4.0) ([PR](https://github.com/arcticicestudio/nord-visual-studio-code/pull/27/files#diff-098616bba15062f029940b60b0c6b009R44)). I see that the color conflicts with the normal code and I think it should be changed to be colorized with nord3 (comment color) instead of nord4 (default code- and variable color).

**Comment by yurlovm** [comment]
Yeah, it would be great!
