### ISSUE TITLE
Scrollbar visibility

### ISSUE THREAD

**Issue by peterdanis** [arcticicestudio/nord-visual-studio-code#41]
Please make the scrollbar more visible.

Before:
![image](https://user-images.githubusercontent.com/26599181/29204203-eb2344a2-7e75-11e7-8a0c-41d435fea04c.png)

After:
![image](https://user-images.githubusercontent.com/26599181/29204213-f5b65198-7e75-11e7-899e-e777b91fd5bf.png)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

The scrollbar might be a bit too dark/transparent in some cases, but I think we should stick to `nord2` with a transparency of 60% (66% on hover and when active) instead of `nord3` which is mainly used as syntax color and might collide when there are long lines of comments.

**Comment by peterdanis** [comment]
Thanks. I have tried it with colors in your commit and it is visible enough.
