### ISSUE TITLE
colors for structs and typedefs

### ISSUE THREAD

**Issue by WLLR9505** [arcticicestudio/nord-visual-studio-code#42]
In C lang, is possible use a color for structs and typedefs?

**Comment by arcticicestudio** [comment]
Sorry for my late reply, unfortunately the time to work on my projects is rare.

Could you please post a example code and a screenshot?

The `struct` and `typedef` keywords should be supported out of the box.

![gh-42-scrot-struct-typedef-keywords](https://user-images.githubusercontent.com/7836623/30780271-8ac4894a-a107-11e7-8710-e7c0c82c6cce.png)

**Comment by arcticicestudio** [comment]
If you meant the name itself there is currently no specific scope provided for it by the default C/C++ syntax highlighting.

![gh-42-scrot-scope](https://user-images.githubusercontent.com/7836623/31055857-bb87cc00-a6c9-11e7-8e35-b097065ca8a8.png)

I'll close this issue for now since there is currently no way to style these, feel free to reopen if you meant another element or if you're aware of a supported solution.
