### ISSUE TITLE
Theme appears to be broken on latest Insiders build

### ISSUE THREAD

**Issue by Plailect** [arcticicestudio/nord-visual-studio-code#5]
On the latest Insiders build (1.11.0-insider, commit 01091bb), the theme seems to only change some colors. I've been using it successfully for several weeks up until it broke a few (?) days ago.

For reference, here are two screenshots comparing the default theme and Nord:

![image](https://cloud.githubusercontent.com/assets/16979510/23826586/d30afbfc-066c-11e7-8496-649d2557d2e4.png)

![image](https://cloud.githubusercontent.com/assets/16979510/23826594/eb610372-066c-11e7-99e4-79167b22d87a.png)

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
Well, since the *Insiders* version is a development build things may break everytime 😉 

There are issues like [Microsoft/vscode #22463](https://github.com/Microsoft/vscode/issues/22463) and [Microsoft/vscode #22361](https://github.com/Microsoft/vscode/issues/22361) about this behavior which are already fiexed in [`56bbea94`](https://github.com/Microsoft/vscode/commit/56bbea94ccd18a96a18641ab6c29c20d198e9585) and [`0e5b61e8`](https://github.com/Microsoft/vscode/commit/0e5b61e8de4187da85780610f21c9d55b6e81e8a).

I've done a small research through the commits and it seems like they are implementing a whole new [theming API](https://github.com/Microsoft/vscode/commit/56bbea94ccd18a96a18641ab6c29c20d198e9585) which uses [*JSON* as theme format instead of *tmTheme*](https://github.com/Microsoft/vscode/commit/99ab6e8d7b0bab5f549c7315d68ce1b299609ae6) ([color scheme validation](https://github.com/Microsoft/vscode/commit/1eb8278296b113a07eaedc3891432de62fd2d2f5)).

I think this is the preparation to provide a way to style the whole VS Code UI like the workbench sidebar, status bar and other UI elements which are currently not styleable via themes.

**Comment by Plailect** [comment]
This appears to be fixed in latest Insiders commits.
