### ISSUE TITLE
The "editor.selectionHighlightBackground" color should have different contrast with "editor.selectionBackground" color

### ISSUE THREAD

**Issue by ooJerryLeeoo** [arcticicestudio/nord-visual-studio-code#59]
By default, the `editor.selectionHighlightBackground` have the same color with `editor.selectionBackground `, it could be confused sometime:

![screen shot 2017-10-29 at 18 34 11](https://user-images.githubusercontent.com/20783502/32142710-cb1e5976-bcd7-11e7-9793-2dc904a6f9c5.png)

In the screenshot I only selected the fourth `a`, but the background highlight is confusing.

The `editor.selectionHighlightBackground` color usually have lower contrast than the `editor.selectionBackground `

For example:

`Default Dark+`

![screen shot 2017-10-29 at 18 38 39](https://user-images.githubusercontent.com/20783502/32142754-8e45c240-bcd8-11e7-9141-d0f1e65a3c60.png)

`Monokai`

![screen shot 2017-10-29 at 18 38 47](https://user-images.githubusercontent.com/20783502/32142757-927c270a-bcd8-11e7-8622-77a5c6aaa100.png)

`Monokai Dimmed`

![screen shot 2017-10-29 at 18 39 28](https://user-images.githubusercontent.com/20783502/32142761-9cf547a2-bcd8-11e7-8e1b-344ae79b56ad.png)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

I'll analyze and reproduce this behavior and see if it should be changed.

**Comment by madprops** [comment]
I agree, it should have a different color to know what is being highlighted and what is being mirrored.

**Comment by arcticicestudio** [comment]
Hi @ooJerryLeeoo  :wave:, sorry for the long delay. I've been really busy with my job, real life and [Nord's, finally launched, official website and documentation](https://www.nordtheme.com).

The problem you're describing is a really tricky one for theme designers since VS Code limits us to only use the theme keys they provide so it is hard to use different colors that match the overall theme style while supporting all the different states:

- **selected** ➜ will highlight other occurrences in the same editor
- **selected**, but **no focus** ➜ will highlight other occurrences in the same editor, but reduces opacity due to focus loss
- highlighted as **find result** by the search widget
  - ➜ allows also to be highlighted as selection **and** as other occurrence

You see there are a lot of states that you need to think of when choosing the colors and there are many themes out there that have the same problem like e.g. the large thread of sdras/night-owl-vscode-theme#90.

In my opinion the case you're describing here is a edge case since it is unusual to have the same words in the exact same indentation on multiple lines exactly with each other. I've tested several opacity settings and different colors and there's not really a case where it might end up in a nice way for all states.

The following screenshots show the current highlighting color with a opacity of 60%. It doesn't really make a large difference when multiple same words are highlighted like on your examples, but it significantly decreases the visual recognizability when words are distributed among a paragraph or within the current active cursor line.

<p align="center"><strong>Current highlighting</strong><br /><img src="https://user-images.githubusercontent.com/7836623/54884339-00e7b680-4e70-11e9-8169-9160bf2b0fe1.png" /></p>

<p align="center"><strong>Significantly decreases visual recognizability with total opacity of 60%</strong><br /><img src="https://user-images.githubusercontent.com/7836623/54884355-3096be80-4e70-11e9-8028-ca311be62183.png" /></p>

<p align="center"><strong>Minimal improvement for edge case and in highly zoomed view</strong><br /><img src="https://user-images.githubusercontent.com/7836623/54884366-4b693300-4e70-11e9-9008-d05ceff27ace.png" /></p>

### Proposed Solution

As you can see, it is unfortunately hard to find a good and well balanced solution for this problem, therefore I don't want to change the theme, but every user who does not like this highlighting can simply fix it using a [theme-scoped workbench color customization](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme):

```jsonc
"workbench.colorCustomizations": {
  "[Nord]": {
    // Colorize automatic occurrences highlights different than selections
    "editor.selectionHighlightBackground": "#434c5e99"
  }
}
```

Adding this snippet to your [user settings](https://code.visualstudio.com/docs/getstarted/settings) and replace the `#434c5e99` with any color you'd like. This will **only apply to the Nord theme** and will **not affect any other themes**.
Also if you want to disable the automatic highlighting of other word occurrences or code variables you can also add this to your settings:

```jsonc
// Disable automatic occurrences highlighting
"editor.occurrencesHighlight": false
```

I hope you can understand this solution and feel free to ask if there are any questions :smile:

**Comment by madprops** [comment]
What I did was add a green-ish color to the main highlight, which might break the theme a little but I prefer having a better idea of the selections:

![Code_2019-03-25_07-32-33](https://user-images.githubusercontent.com/206498/54923637-463bd080-4ed0-11e9-8de6-9dc1e196a156.jpg)

I made this and other changes into a new theme which you can find here: https://marketplace.visualstudio.com/items?itemName=madprops.nordico
