### ISSUE TITLE
Flow annotation support

### ISSUE THREAD

**Issue by vomchik** [arcticicestudio/nord-visual-studio-code#65]
Before:
![before](https://user-images.githubusercontent.com/732085/35744731-b75f3bd6-0849-11e8-8fd4-a0a7537d3c70.png)

After:
![after](https://user-images.githubusercontent.com/732085/35744730-b743273e-0849-11e8-9173-d96d30b173a1.png)

As you can see `export const appStateChannel` lost own color definition.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

Have you tried to reproduce it with other color themes? At first glance, it looks to me like this is more related to the language syntax parser since there should be no difference when the previous line contains elements currently not supported by the color theme.

**Comment by vomchik** [comment]
Hm, I will check this later. Stay tuned 🙂

**Comment by arcticicestudio** [comment]
@vomchik Any progress on this issue, have you been able to fix the problem or is it still present? If yes it'd be nice if you can explain how you fixed it or if it was fixed by the upstream (VS Code).

**Comment by vomchik** [comment]
Hey, sorry for the delay. No, i don't know how we can fix it. I guess it a vscode's issue, not the theme.

**Comment by arcticicestudio** [comment]
Hi again @vomchik :wave: 
I'll close this issue for now since it has been stale for a long time now and it seems like that this was (is?) not a problem of the Nord theme but VS Code or the extension that provides the language syntax definitions.

I've tried reproduce the problem, but it looks like it was fixed at least for the default bundled JavaScript language syntax definitions and the the most advanced [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) extension.

![gh-65-commented](https://user-images.githubusercontent.com/7836623/54863662-b5d48300-4d4b-11e9-8081-cb1110be2a9a.png)

![gh-65-uncommented](https://user-images.githubusercontent.com/7836623/54863665-b8cf7380-4d4b-11e9-8494-cc249fe5a216.png)

If you're still affected by this problem feel free to comment here and I'll reopen the issue so we can take a deeper look into it.
