### ISSUE TITLE
Suggestion: Higher-contrast version

### ISSUE THREAD

**Issue by m-thorsen** [arcticicestudio/nord-visual-studio-code#68]
Love the theme, but I had to make a couple of tweaks as I found it a tad too pale for late night sessions.  
Not sure how active this project is, but I'll share them here in case you'd like to add an alternative variant.

I'm aware that the darker colors are outside the Nord palette, but I think it looks fairly decent without going overboard (like some forks I've seen).

```json
"workbench.colorCustomizations": {
    "editor.selectionHighlightBackground": "#2e3440",
    "editor.selectionHighlightBorder": "#FFFFFF15",
    "editor.background": "#272c36",
    "editorGutter.background": "#272c36",
    "tab.activeBackground": "#2e3440",
    "tab.inactiveBackground": "#272c36",
    "editorGroupHeader.tabsBackground": "#272c36",
    "editorGroupHeader.tabsBorder": "#2e3440",
    "editorLineNumber.foreground": "#4C566A"
},
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "Comment",
            "scope": "comment",
            "settings": {
                "foreground": "#576279",
                "fontStyle": "italic"
            }
        }
    ]
},
```

![image](https://user-images.githubusercontent.com/14907694/39604503-b897eb9a-4f2c-11e8-80bc-37165514db50.png)

**Comment by arcticicestudio** [comment]
:rocket: Thanks for your contribution :+1: 

This might be interesting for users who'd also like to tweak some parts of the theme to fit their personal preferences. Everyone has different needs and preferences and that's the whole reason why themes exist ;p

Regarding your changes to the comment color: This is a long time requested change in many Nord port projects and that's why there will be official changes. Check out the [poll about comment brightness adjustments][poll] for more details.

Also, I think you opened this issue because your posted changes would also override other themes. To prevent this VS Code allows you to [define overrides scoped for a specific theme][vsdoc] by using the theme name like this:

```json5
"workbench.colorCustomizations": {
    "[Nord]": {
        // Place your overrides here 
    }
}
```

This can also be used for syntax theme overrides:

```json5
"editor.tokenColorCustomizations": {
    "[Nord]": {
        // Place your overrides here 
    }
},
```

So, to prevent your customizations from overriding other themes than  _Nord_ it should be changed to something similar like this:

```json5
  "workbench.colorCustomizations": {
    "[Nord]": {
      "editor.selectionHighlightBackground": "#2e3440",
      "editor.selectionHighlightBorder": "#FFFFFF15",
      "editor.background": "#272c36",
      "editorGutter.background": "#272c36",
      "tab.activeBackground": "#2e3440",
      "tab.inactiveBackground": "#272c36",
      "editorGroupHeader.tabsBackground": "#272c36",
      "editorGroupHeader.tabsBorder": "#2e3440",
      "editorLineNumber.foreground": "#4C566A"
    }
  },
  "editor.tokenColorCustomizations": {
    "[Nord]": {
      "textMateRules": [
        {
          "name": "Comment",
          "scope": "comment",
          "settings": {
            "foreground": "#576279",
            "fontStyle": "italic"
          }
        }
      ]
    }
  }
```

[poll]: https://github.com/arcticicestudio/nord/issues/94
[vsdoc]: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
